name: Demo test

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
#      - name: Start selenoid
#        uses: Xotabu4/selenoid-github-action@v2
      - run: mvn clean test -Dsuite=dummy
      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report
          destination_dir: subdir
#      - name: Notify about smoke test fail on Slack
#        id: slack
#        uses: slackapi/slack-github-action@v1.18.0
#        with:
#        # For posting a rich message using Block Kit
#          payload: |
#              {
#                "blocks": [
#                  {
#                    "type": "section",
#                    "text": {
#                      "type": "mrkdwn",
#                      "text": "Smoke test is failed\nLatest report can be found here https://special-eureka-17b44353.pages.github.io/"
#                    }
#                  }
#                ]
#              }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
